version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: sudo npm install dredd --global --unsafe-perm=true --allow-root
      - run: npm install express
      - run: dredd
